export const CATEGORIES = {
  FRONT_END: 1,
  FULL_STACK: 19,
  LITERATURE: 37,
  DIARY: 41
}

export const CATEGORY_NAMES = {
  [CATEGORIES.FRONT_END]: '前端领域',
  [CATEGORIES.FULL_STACK]: '全栈领域',
  [CATEGORIES.LITERATURE]: '网络文学',
  [CATEGORIES.DIARY]: '生活感悟',
}